project:
  type: website
  output-dir: docs

website:
  title: "Eikosany - Cascadia R Conference Slides"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Eikosany-Cascadia-R-Conference-Slides.qmd
      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

