---
title: "Eikosany: Microtonal Algorithmic Composition with R"
author: "M. Edward (Ed) Borasky"
date: "2023-08-19"
bibliography: REFERENCES.bib
output:
  beamer_presentation:
    theme: "Montpellier"
    incremental: false
    slide_level: 2
---

# Algorithmic Composition

## Overview of Methods [@nierhaus2009algorithmic]

-   Markov Models / Stochastic
-   Generative Grammars
-   Transition Networks
-   Chaos and Self-Similarity
-   Genetic Algorithms
-   Cellular Automata
-   Artificial Neural Networks

## My Main Focus

-   Markov Models / Stochastic
    -   Pioneered by Iannis Xenakis [@xenakis1992formalized]
    -   [for example, @Borasky2021a - random walks on chord matrix]

# Musical Scales

## Types of scales

-   Standard "western" tuning - 12 equally-spaced tones / octave
    -   abbreviated 12-TET or 12-EDO
-   Alternative tuning - anything else
    -   scales from other cultures
    -   "just" scales - scales based on rational numbers
    -   scale periods different from the octave
    -   scale period divided into more than 12 tones
    -   combinations of the above!

## Microtonal music

-   Usually defined as an octave divided into more than 12 tones
-   Common microtonal scales
    -   19-TET
    -   24-TET aka quarter tones
    -   31-TET

# Erv Wilson [@narushima2019microtonality]

# Current Outputs / Workflow

# Roadmap

# References
